# Generated by Django 2.0.7 on 2019-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='test',
            field=models.IntegerField(default=2),
        ),
    ]
